[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.5"

[[repos.hooks]]
id = "ruff-check"
args = ["--fix"]
types_or = ["python", "pyi" ]
#args = ["--fix", "--exit-zero"]
[[repos.hooks]]
id = "ruff-format"