# generated by datamodel-codegen:
#   filename:  ShipServiceDefinitions-OpenApi31Yaml.yaml
#   timestamp: 2024-02-17T19:09:14+00:00

from __future__ import annotations

from typing import List, Optional
from enum import Enum

from pydantic import Field

from shipr.models.bases import BasePFType, BaseReply, BaseRequest


class FindMessage(BasePFType):
    convenient_collect: Optional[ConvenientCollect] = Field(
        None
    )
    specified_post_office: Optional[SpecifiedPostOffice] = Field(
        None
    )
    paf: Optional[PAF] = Field(None, alias='PAF')
    safe_places: Optional[bool] = Field(None)
    nominated_delivery_dates: Optional[NominatedDeliveryDates] = Field(
        None
    )
    postcode_exclusion: Optional[PostcodeExclusion] = Field(
        None
    )


class FindRequest(FindMessage, BaseRequest):
    ...


class FindReply(FindMessage, BaseReply):
    ...


class PAF(BasePFType):
    postcode: Optional[str] = Field(None)
    count: Optional[int] = Field(None)
    specified_neighbour: Optional[List[SpecifiedNeighbour]] = Field(
        None, description=''
    )


class Notifications(BasePFType):
    notification_type: List[str] = Field(..., description='')


class Address(BasePFType):
    address_line1: str = Field(...)
    address_line2: Optional[str] = Field(None)
    address_line3: Optional[str] = Field(None)
    town: Optional[str] = Field(None)
    postcode: Optional[str] = Field(None)
    country: str = Field(...)


class Enhancement(BasePFType):
    enhanced_compensation: Optional[str] = Field(None)
    saturday_delivery_required: Optional[bool] = Field(
        None
    )


class HazardousGood(BasePFType):
    lqdgun_code: Optional[str] = Field(None)
    lqdg_description: Optional[str] = Field(None)
    lqdg_volume: Optional[float] = Field(None)
    firearms: Optional[str] = Field(None)


class Returns(BasePFType):
    returns_email: Optional[str] = Field(None)
    email_message: Optional[str] = Field(None)
    email_label: bool = Field(...)


class ContentDetail(BasePFType):
    country_of_manufacture: str = Field(...)
    country_of_origin: Optional[str] = Field(None)
    manufacturers_name: Optional[str] = Field(None)
    description: str = Field(...)
    unit_weight: float = Field(...)
    unit_quantity: int = Field(...)
    unit_value: float = Field(...)
    currency: str = Field(...)
    tariff_code: Optional[str] = Field(None)
    tariff_description: Optional[str] = Field(None)
    article_reference: Optional[str] = Field(None)


class DateTimeRange(BasePFType):
    from_: str = Field(...)
    to: str = Field(...)


class ContentData(BasePFType):
    name: str = Field(...)
    data: str = Field(...)


class LabelItem(BasePFType):
    name: str = Field(...)
    data: str = Field(...)


class Barcode(BasePFType):
    name: str = Field(...)
    data: str = Field(...)


class Image(BasePFType):
    name: str = Field(...)
    data: str = Field(...)


class PrintType(Enum):
    all_parcels = 'ALL_PARCELS'
    single_parcel = 'SINGLE_PARCEL'


class Document(BasePFType):
    data: str = Field(...)


class ManifestShipment(BasePFType):
    shipment_number: str = Field(...)
    service_code: str = Field(...)


class CompletedShipment(BasePFType):
    shipment_number: Optional[str] = Field(None)
    out_bound_shipment_number: Optional[str] = Field(
        None
    )
    in_bound_shipment_number: Optional[str] = Field(None)
    partner_number: Optional[str] = Field(None)


class CompletedReturnInfo(BasePFType):
    status: str = Field(...)
    shipment_number: str = Field(...)
    collection_time: DateTimeRange = Field(...)


class Authentication(BasePFType):
    user_name: str = Field(...)
    password: str = Field(...)


class CompletedCancelInfo(BasePFType):
    status: Optional[str] = Field(None)
    shipment_number: Optional[str] = Field(None)


class SpecifiedNeighbour(BasePFType):
    address: Optional[List[Address]] = Field(None, description='')


class SafePlaceList(BasePFType):
    safe_place: Optional[List[str]] = Field(None, description='')


class NominatedDeliveryDateList(BasePFType):
    nominated_delivery_date: Optional[List[str]] = Field(
        None, description=''
    )


class ServiceCodes(BasePFType):
    service_code: Optional[List[str]] = Field(None, description='')


class Hours(BasePFType):
    open: Optional[str] = Field(None)
    close: Optional[str] = Field(None)
    close_lunch: Optional[str] = Field(None)
    after_lunch_opening: Optional[str] = Field(None)


class Position(BasePFType):
    longitude: Optional[float] = Field(None)
    latitude: Optional[float] = Field(None)


class AlertType(Enum):
    error = 'ERROR'
    warning = 'WARNING'
    notification = 'NOTIFICATION'


class Contact(BasePFType):
    business_name: str = Field(...)
    contact_name: Optional[str] = Field(None)
    email_address: Optional[str] = Field(None)
    telephone: Optional[str] = Field(None)
    fax: Optional[str] = Field(None)
    mobile_phone: Optional[str] = Field(None)
    senders_name: Optional[str] = Field(None)
    notifications: Optional[Notifications] = Field(None)


class InBoundDetails(BasePFType):
    contract_number: str = Field(...)
    service_code: str = Field(...)
    total_shipment_weight: Optional[str] = Field(None)
    enhancement: Optional[Enhancement] = Field(None)
    reference_number1: Optional[str] = Field(None)
    reference_number2: Optional[str] = Field(None)
    reference_number3: Optional[str] = Field(None)
    reference_number4: Optional[str] = Field(None)
    reference_number5: Optional[str] = Field(None)
    special_instructions1: Optional[str] = Field(None)
    special_instructions2: Optional[str] = Field(None)
    special_instructions3: Optional[str] = Field(None)
    special_instructions4: Optional[str] = Field(None)


class HazardousGoods(BasePFType):
    hazardous_good: List[HazardousGood] = Field(
        ..., description=''
    )


class ContentDetails(BasePFType):
    content_detail: List[ContentDetail] = Field(
        ..., description=''
    )


class CollectionInfo(BasePFType):
    collection_contact: Contact = Field(...)
    collection_address: Address = Field(...)
    collection_time: Optional[DateTimeRange] = Field(None)


class ParcelContents(BasePFType):
    item: List[ContentData] = Field(..., description='')


class LabelData(BasePFType):
    item: List[LabelItem] = Field(..., description='')


class Barcodes(BasePFType):
    barcode: List[Barcode] = Field(..., description='')


class Images(BasePFType):
    image: List[Image] = Field(..., description='')


class ManifestShipments(BasePFType):
    manifest_shipment: List[ManifestShipment] = Field(
        ..., description=''
    )


class CompletedShipments(BasePFType):
    completed_shipment: List[CompletedShipment] = Field(
        ..., description=''
    )


class Alert(BasePFType):
    code: int = Field(...)
    message: str = Field(...)
    type: AlertType = Field(...)


class CompletedCancel(BasePFType):
    completed_cancel_info: Optional[CompletedCancelInfo] = Field(
        None
    )


def snake_to_upper(s: str) -> str:
    return s.upper()


class Department(BasePFType):
    department_id: Optional[List[int]] = Field(
        None, description=''
    )
    service_codes: Optional[List[ServiceCodes]] = Field(
        None, description=''
    )
    nominated_delivery_date_list: Optional[NominatedDeliveryDateList] = Field(
        None
    )


class Mon(BasePFType):
    hours: Optional[Hours] = Field(None)


class Tue(BasePFType):
    hours: Optional[Hours] = Field(None)


class Wed(BasePFType):
    hours: Optional[Hours] = Field(None)


class Thu(BasePFType):
    hours: Optional[Hours] = Field(None)


class Fri(BasePFType):
    hours: Optional[Hours] = Field(None)


class Sat(BasePFType):
    hours: Optional[Hours] = Field(None)


class Sun(BasePFType):
    hours: Optional[Hours] = Field(None)


class BankHol(BasePFType):
    hours: Optional[Hours] = Field(None)


class PrintLabelRequest(BaseRequest):
    shipment_number: str = Field(...)
    print_format: Optional[str] = Field(None)
    barcode_format: Optional[str] = Field(None)
    print_type: Optional[PrintType] = Field(None)


class PrintDocumentRequest(BaseRequest):
    shipment_number: str = Field(...)
    document_type: int = Field(...)
    print_format: Optional[str] = Field(None)


class CreateManifestRequest(BaseRequest):
    department_id: Optional[int] = Field(None)


class PrintManifestRequest(BaseRequest):
    manifest_number: str = Field(...)
    print_format: Optional[str] = Field(None)


class ReturnShipmentRequest(BaseRequest):
    shipment_number: str = Field(...)
    collection_time: DateTimeRange = Field(...)


class CCReserveRequest(BaseRequest):
    booking_reference: str = Field(...)


class CancelShipmentRequest(BaseRequest):
    shipment_number: str = Field(...)


class Parcel(BasePFType):
    weight: Optional[float] = Field(None)
    length: Optional[int] = Field(None)
    height: Optional[int] = Field(None)
    width: Optional[int] = Field(None)
    purpose_of_shipment: Optional[str] = Field(None)
    invoice_number: Optional[str] = Field(None)
    export_license_number: Optional[str] = Field(None)
    certificate_number: Optional[str] = Field(None)
    content_details: Optional[ContentDetails] = Field(None)
    shipping_cost: Optional[float] = Field(None)


class ParcelLabelData(BasePFType):
    parcel_number: Optional[str] = Field(None)
    shipment_number: Optional[str] = Field(None)
    journey_leg: Optional[str] = Field(None)
    label_data: Optional[LabelData] = Field(None)
    barcodes: Optional[Barcodes] = Field(None)
    images: Optional[Images] = Field(None)
    parcel_contents: Optional[List[ParcelContents]] = Field(
        None, description=''
    )


class CompletedManifestInfo(BasePFType):
    department_id: int = Field(...)
    manifest_number: str = Field(...)
    manifest_type: str = Field(...)
    total_shipment_count: int = Field(...)
    manifest_shipments: ManifestShipments = Field(...)


class CompletedShipmentInfoCreatePrint(BasePFType):
    lead_shipment_number: Optional[str] = Field(None)
    shipment_number: Optional[str] = Field(None)
    delivery_date: Optional[str] = Field(None)
    status: str = Field(...)
    completed_shipments: CompletedShipments = Field(...)


class Alerts(BasePFType):
    alert: List[Alert] = Field(..., description='')


class Departments(BasePFType):
    department: Optional[List[Department]] = Field(
        None, description=''
    )


class OpeningHours(BasePFType):
    mon: Optional[Mon] = Field(None)
    tue: Optional[Tue] = Field(None)
    wed: Optional[Wed] = Field(None)
    thu: Optional[Thu] = Field(None)
    fri: Optional[Fri] = Field(None)
    sat: Optional[Sat] = Field(None)
    sun: Optional[Sun] = Field(None)
    bank_hol: Optional[BankHol] = Field(None)


class CancelShipmentRequest1(BasePFType):
    cancel_shipment_request: CancelShipmentRequest = Field(
        ...
    )


class CCReserveRequest1(BasePFType):
    cc_reserve_request: CCReserveRequest = Field(...)


class CreateManifestRequest1(BasePFType):
    create_manifest_request: CreateManifestRequest = Field(
        ...
    )


class PrintDocumentRequest1(BasePFType):
    print_document_request: PrintDocumentRequest = Field(
        ...
    )


class PrintLabelRequest1(BasePFType):
    print_label_request: PrintLabelRequest = Field(...)


class PrintManifestRequest1(BasePFType):
    print_manifest_request: PrintManifestRequest = Field(
        ...
    )


class ReturnShipmentRequest1(BasePFType):
    return_shipment_request: ReturnShipmentRequest = Field(
        ...
    )


class Parcels(BasePFType):
    parcel: List[Parcel] = Field(..., description='')


class ShipmentLabelData(BasePFType):
    parcel_label_data: List[ParcelLabelData] = Field(
        ..., description=''
    )


class CompletedManifests(BasePFType):
    completed_manifest_info: List[CompletedManifestInfo] = Field(
        ..., description=''
    )


class NominatedDeliveryDates(BasePFType):
    service_code: Optional[str] = Field(None)
    departments: Optional[Departments] = Field(None)


class PostcodeExclusion(BasePFType):
    delivery_postcode: Optional[str] = Field(None)
    collection_postcode: Optional[str] = Field(None)
    departments: Optional[Departments] = Field(None)


class PostOffice(BasePFType):
    post_office_id: Optional[str] = Field(None)
    business: Optional[str] = Field(None)
    address: Optional[Address] = Field(None)
    opening_hours: Optional[OpeningHours] = Field(None)
    distance: Optional[float] = Field(None)
    availability: Optional[bool] = Field(None)
    position: Optional[Position] = Field(None)
    booking_reference: Optional[str] = Field(None)


class CreatePrintReply(BaseReply):
    completed_shipment_info_create_print: Optional[CompletedShipmentInfoCreatePrint] = (
        Field(None)
    )
    label: Optional[Document] = Field(None)
    label_data: Optional[ShipmentLabelData] = Field(None)
    partner_code: Optional[str] = Field(None)


class PrintLabelReply(BaseReply):
    label: Optional[Document] = Field(None)
    label_data: Optional[ShipmentLabelData] = Field(None)
    partner_code: Optional[str] = Field(None)


class PrintDocumentReply(BaseReply):
    label: Optional[Document] = Field(None)
    label_data: Optional[ShipmentLabelData] = Field(None)
    document_type: Optional[Document] = Field(None)


class CreateManifestReply(BaseReply):
    completed_manifests: Optional[CompletedManifests] = Field(
        None
    )


class PrintManifestReply(BaseReply):
    manifest: Optional[Document] = Field(None)


class ReturnShipmentReply(BaseReply):
    completed_shipment_info: Optional[CompletedReturnInfo] = Field(
        None
    )


class CCReserveReply(BaseReply):
    post_office: Optional[PostOffice] = Field(None)


class CancelShipmentReply(BaseReply):
    completed_cancel: Optional[CompletedCancel] = Field(None)


class InternationalInfo(BasePFType):
    parcels: Optional[Parcels] = Field(None)
    exporter_customs_reference: Optional[str] = Field(
        None
    )
    recipient_importer_vat_no: Optional[str] = Field(
        None
    )
    original_export_shipment_no: Optional[str] = Field(
        None
    )
    documents_only: Optional[bool] = Field(None)
    documents_description: Optional[str] = Field(None)
    value_under200_us_dollars: Optional[bool] = Field(
        None
    )
    shipment_description: Optional[str] = Field(None)
    comments: Optional[str] = Field(None)
    invoice_date: Optional[str] = Field(None)
    terms_of_delivery: Optional[str] = Field(None)
    purchase_order_ref: Optional[str] = Field(None)


class ConvenientCollect(BasePFType):
    postcode: Optional[str] = Field(None)
    post_office: Optional[List[PostOffice]] = Field(
        None, description=''
    )
    count: Optional[int] = Field(None)
    post_office_id: Optional[str] = Field(None)


class SpecifiedPostOffice(BasePFType):
    postcode: Optional[str] = Field(None)
    post_office: Optional[List[PostOffice]] = Field(
        None, description=''
    )
    count: Optional[int] = Field(None)
    post_office_id: Optional[str] = Field(None)


class CancelShipmentReply1(BasePFType):
    cancel_shipment_reply: CancelShipmentReply = Field(...)


class CCReserveReply1(BasePFType):
    cc_reserve_reply: CCReserveReply = Field(...)


class CreateManifestReply1(BasePFType):
    create_manifest_reply: CreateManifestReply = Field(...)


class CreatePrintReply1(BasePFType):
    create_print_reply: CreatePrintReply = Field(...)


class PrintDocumentReply1(BasePFType):
    print_document_reply: PrintDocumentReply = Field(...)


class PrintLabelReply1(BasePFType):
    print_label_reply: PrintLabelReply = Field(...)


class PrintManifestReply1(BasePFType):
    print_manifest_reply: PrintManifestReply = Field(...)


class ReturnShipmentReply1(BasePFType):
    return_shipment_reply: ReturnShipmentReply = Field(...)


class DeliveryOptions(BasePFType):
    convenient_collect: Optional[ConvenientCollect] = Field(
        None
    )
    irts: Optional[bool] = Field(None)
    letterbox: Optional[bool] = Field(None)
    specified_post_office: Optional[SpecifiedPostOffice] = Field(
        None
    )
    specified_neighbour: Optional[str] = Field(None)
    safe_place: Optional[str] = Field(None)
    pin: Optional[int] = Field(None)
    named_recipient: Optional[bool] = Field(None)
    address_only: Optional[bool] = Field(None)
    nominated_delivery_date: Optional[str] = Field(None)
    personal_parcel: Optional[str] = Field(None)


class FindReply1(BasePFType):
    find_reply: FindReply = Field(...)


class FindRequest1(BasePFType):
    find_request: FindRequest = Field(...)


class RequestedShipment(BasePFType):
    department_id: Optional[int] = Field(None)
    shipment_type: str = Field(...)
    contract_number: str = Field(...)
    request_id: Optional[int] = Field(None)
    service_code: str = Field(...)
    pre_printed: Optional[bool] = Field(None)
    shipping_date: Optional[str] = Field(None)
    job_reference: Optional[str] = Field(None)
    recipient_contact: Contact = Field(...)
    recipient_address: Address = Field(...)
    importer_contact: Optional[Contact] = Field(None)
    importer_address: Optional[Address] = Field(None)
    exporter_contact: Optional[Contact] = Field(None)
    exporter_address: Optional[Address] = Field(None)
    sender_contact: Optional[Contact] = Field(None)
    sender_address: Optional[Address] = Field(None)
    total_number_of_parcels: Optional[int] = Field(None)
    total_shipment_weight: Optional[float] = Field(None)
    enhancement: Optional[Enhancement] = Field(None)
    delivery_options: Optional[DeliveryOptions] = Field(None)
    hazardous_goods: Optional[HazardousGoods] = Field(None)
    returns: Optional[Returns] = Field(None)
    drop_off_ind: Optional[str] = Field(None)
    print_own_label: Optional[bool] = Field(None)
    collection_info: Optional[CollectionInfo] = Field(None)
    international_info: Optional[InternationalInfo] = Field(
        None
    )
    reference_number1: Optional[str] = Field(None)
    reference_number2: Optional[str] = Field(None)
    reference_number3: Optional[str] = Field(None)
    reference_number4: Optional[str] = Field(None)
    reference_number5: Optional[str] = Field(None)
    special_instructions1: Optional[str] = Field(None)
    special_instructions2: Optional[str] = Field(None)
    special_instructions3: Optional[str] = Field(None)
    special_instructions4: Optional[str] = Field(None)
    in_bound_contact: Optional[Contact] = Field(None)
    in_bound_address: Optional[Address] = Field(None)
    in_bound_details: Optional[InBoundDetails] = Field(None)
    exchange_instructions1: Optional[str] = Field(None)
    exchange_instructions2: Optional[str] = Field(None)
    exchange_instructions3: Optional[str] = Field(None)
    consignment_handling: Optional[bool] = Field(None)


class CompletedShipmentInfo(BasePFType):
    lead_shipment_number: Optional[str] = Field(None)
    delivery_date: Optional[str] = Field(None)
    status: str = Field(...)
    completed_shipments: CompletedShipments = Field(...)
    requested_shipment: RequestedShipment = Field(...)


class CreateShipmentRequest(BaseRequest):
    requested_shipment: RequestedShipment = Field(...)


class CreateShipmentReply(BaseReply):
    completed_shipment_info: Optional[CompletedShipmentInfo] = Field(
        None
    )


class CreatePrintRequest(BaseRequest):
    requested_shipment: RequestedShipment = Field(...)


class CreatePrintRequest1(BasePFType):
    create_print_request: CreatePrintRequest = Field(...)


class CreateShipmentReply1(BasePFType):
    create_shipment_reply: CreateShipmentReply = Field(...)


class CreateShipmentRequest1(BasePFType):
    create_shipment_request: CreateShipmentRequest = Field(
        ...
    )
