# generated by datamodel-codegen:
#   filename:  ShipServiceDefinitions-OpenApi31Yaml.yaml
#   timestamp: 2024-02-17T18:04:40+00:00
 # pre-converted from wsdl to yaml with apimatic

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Notifications(BaseModel):
    NotificationType: list[str] = Field(..., description='')


class Address(BaseModel):
    AddressLine1: str
    AddressLine2: str | None = None
    AddressLine3: str | None = None
    Town: str | None = None
    Postcode: str | None = None
    Country: str


class Enhancement(BaseModel):
    EnhancedCompensation: str | None = None
    SaturdayDeliveryRequired: bool | None = None


class HazardousGood(BaseModel):
    LQDGUNCode: str | None = None
    LQDGDescription: str | None = None
    LQDGVolume: float | None = None
    Firearms: str | None = None


class Returns(BaseModel):
    ReturnsEmail: str | None = None
    EmailMessage: str | None = None
    EmailLabel: bool


class ContentDetail(BaseModel):
    CountryOfManufacture: str
    CountryOfOrigin: str | None = None
    ManufacturersName: str | None = None
    Description: str
    UnitWeight: float
    UnitQuantity: int
    UnitValue: float
    Currency: str
    TariffCode: str | None = None
    TariffDescription: str | None = None
    ArticleReference: str | None = None


class DateTimeRange(BaseModel):
    From: str
    To: str


class ContentData(BaseModel):
    Name: str
    Data: str


class LabelItem(BaseModel):
    Name: str
    Data: str


class Barcode(BaseModel):
    Name: str
    Data: str


class Image(BaseModel):
    Name: str
    Data: str


class PrintType(Enum):
    ALL_PARCELS = 'ALL_PARCELS'
    SINGLE_PARCEL = 'SINGLE_PARCEL'


class Document(BaseModel):
    Data: str


class ManifestShipment(BaseModel):
    ShipmentNumber: str
    ServiceCode: str


class CompletedShipment(BaseModel):
    ShipmentNumber: str | None = None
    OutBoundShipmentNumber: str | None = None
    InBoundShipmentNumber: str | None = None
    PartnerNumber: str | None = None


class CompletedReturnInfo(BaseModel):
    Status: str
    ShipmentNumber: str
    CollectionTime: DateTimeRange


class Authentication(BaseModel):
    UserName: str
    Password: str


class CompletedCancelInfo(BaseModel):
    Status: str | None = None
    ShipmentNumber: str | None = None


class SpecifiedNeighbour(BaseModel):
    Address: list[Address] | None = Field(None, description='')


class SafePlaceList(BaseModel):
    SafePlace: list[str] | None = Field(None, description='')


class NominatedDeliveryDateList(BaseModel):
    NominatedDeliveryDate: list[str] | None = Field(None, description='')


class ServiceCodes(BaseModel):
    ServiceCode: list[str] | None = Field(None, description='')


class Hours(BaseModel):
    Open: str | None = None
    Close: str | None = None
    CloseLunch: str | None = None
    AfterLunchOpening: str | None = None


class Position(BaseModel):
    Longitude: float | None = None
    Latitude: float | None = None


class AlertType(Enum):
    ERROR = 'ERROR'
    WARNING = 'WARNING'
    NOTIFICATION = 'NOTIFICATION'


class BaseRequest(BaseModel):
    Authentication: Authentication


class Contact(BaseModel):
    BusinessName: str
    ContactName: str | None = None
    EmailAddress: str | None = None
    Telephone: str | None = None
    Fax: str | None = None
    MobilePhone: str | None = None
    SendersName: str | None = None
    Notifications: Notifications | None = None


class InBoundDetails(BaseModel):
    ContractNumber: str
    ServiceCode: str
    TotalShipmentWeight: str | None = None
    Enhancement: Enhancement | None = None
    ReferenceNumber1: str | None = None
    ReferenceNumber2: str | None = None
    ReferenceNumber3: str | None = None
    ReferenceNumber4: str | None = None
    ReferenceNumber5: str | None = None
    SpecialInstructions1: str | None = None
    SpecialInstructions2: str | None = None
    SpecialInstructions3: str | None = None
    SpecialInstructions4: str | None = None


class HazardousGoods(BaseModel):
    HazardousGood: list[HazardousGood] = Field(..., description='')


class ContentDetails(BaseModel):
    ContentDetail: list[ContentDetail] = Field(..., description='')


class CollectionInfo(BaseModel):
    CollectionContact: Contact
    CollectionAddress: Address
    CollectionTime: DateTimeRange | None = None


class ParcelContents(BaseModel):
    Item: list[ContentData] = Field(..., description='')


class LabelData(BaseModel):
    Item: list[LabelItem] = Field(..., description='')


class Barcodes(BaseModel):
    Barcode: list[Barcode] = Field(..., description='')


class Images(BaseModel):
    Image: list[Image] = Field(..., description='')


class ManifestShipments(BaseModel):
    ManifestShipment: list[ManifestShipment] = Field(..., description='')


class CompletedShipments(BaseModel):
    CompletedShipment: list[CompletedShipment] = Field(..., description='')


class Alert(BaseModel):
    Code: int
    Message: str
    Type: AlertType


class CompletedCancel(BaseModel):
    CompletedCancelInfo: CompletedCancelInfo | None = None


class PAF(BaseModel):
    Postcode: str | None = None
    Count: int | None = None
    SpecifiedNeighbour: list[SpecifiedNeighbour] | None = Field(None, description='')


class Department(BaseModel):
    DepartmentID: list[int] | None = Field(None, description='')
    ServiceCodes: list[ServiceCodes] | None = Field(None, description='')
    NominatedDeliveryDateList: NominatedDeliveryDateList | None = None


class Mon(BaseModel):
    Hours: Hours | None = None


class Tue(BaseModel):
    Hours: Hours | None = None


class Wed(BaseModel):
    Hours: Hours | None = None


class Thu(BaseModel):
    Hours: Hours | None = None


class Fri(BaseModel):
    Hours: Hours | None = None


class Sat(BaseModel):
    Hours: Hours | None = None


class Sun(BaseModel):
    Hours: Hours | None = None


class BankHol(BaseModel):
    Hours: Hours | None = None


class PrintLabelRequest(BaseRequest):
    ShipmentNumber: str
    PrintFormat: str | None = None
    BarcodeFormat: str | None = None
    PrintType: PrintType | None = None


class PrintDocumentRequest(BaseRequest):
    ShipmentNumber: str
    DocumentType: int
    PrintFormat: str | None = None


class CreateManifestRequest(BaseRequest):
    DepartmentId: int | None = None


class PrintManifestRequest(BaseRequest):
    ManifestNumber: str
    PrintFormat: str | None = None


class ReturnShipmentRequest(BaseRequest):
    ShipmentNumber: str
    CollectionTime: DateTimeRange


class CCReserveRequest(BaseRequest):
    BookingReference: str


class CancelShipmentRequest(BaseRequest):
    ShipmentNumber: str


class Parcel(BaseModel):
    Weight: float | None = None
    Length: int | None = None
    Height: int | None = None
    Width: int | None = None
    PurposeOfShipment: str | None = None
    InvoiceNumber: str | None = None
    ExportLicenseNumber: str | None = None
    CertificateNumber: str | None = None
    ContentDetails: ContentDetails | None = None
    ShippingCost: float | None = None


class ParcelLabelData(BaseModel):
    ParcelNumber: str | None = None
    ShipmentNumber: str | None = None
    JourneyLeg: str | None = None
    LabelData: LabelData | None = None
    Barcodes: Barcodes | None = None
    Images: Images | None = None
    ParcelContents: list[ParcelContents] | None = Field(None, description='')


class CompletedManifestInfo(BaseModel):
    DepartmentId: int
    ManifestNumber: str
    ManifestType: str
    TotalShipmentCount: int
    ManifestShipments: ManifestShipments


class CompletedShipmentInfoCreatePrint(BaseModel):
    LeadShipmentNumber: str | None = None
    ShipmentNumber: str | None = None
    DeliveryDate: str | None = None
    Status: str
    CompletedShipments: CompletedShipments


class Alerts(BaseModel):
    Alert: list[Alert] = Field(..., description='')


class Departments(BaseModel):
    Department: list[Department] | None = Field(None, description='')


class OpeningHours(BaseModel):
    Mon: Mon | None = None
    Tue: Tue | None = None
    Wed: Wed | None = None
    Thu: Thu | None = None
    Fri: Fri | None = None
    Sat: Sat | None = None
    Sun: Sun | None = None
    BankHol: BankHol | None = None


class CancelShipmentRequest1(BaseModel):
    CancelShipmentRequest: CancelShipmentRequest


class CCReserveRequest1(BaseModel):
    CCReserveRequest: CCReserveRequest


class CreateManifestRequest1(BaseModel):
    CreateManifestRequest: CreateManifestRequest


class PrintDocumentRequest1(BaseModel):
    PrintDocumentRequest: PrintDocumentRequest


class PrintLabelRequest1(BaseModel):
    PrintLabelRequest: PrintLabelRequest


class PrintManifestRequest1(BaseModel):
    PrintManifestRequest: PrintManifestRequest


class ReturnShipmentRequest1(BaseModel):
    ReturnShipmentRequest: ReturnShipmentRequest


class BaseReply(BaseModel):
    Alerts: Alerts | None = None


class Parcels(BaseModel):
    Parcel: list[Parcel] = Field(..., description='')


class ShipmentLabelData(BaseModel):
    ParcelLabelData: list[ParcelLabelData] = Field(..., description='')


class CompletedManifests(BaseModel):
    CompletedManifestInfo: list[CompletedManifestInfo] = Field(..., description='')


class NominatedDeliveryDates(BaseModel):
    ServiceCode: str | None = None
    Departments: Departments | None = None


class PostcodeExclusion(BaseModel):
    DeliveryPostcode: str | None = None
    CollectionPostcode: str | None = None
    Departments: Departments | None = None


class PostOffice(BaseModel):
    PostOfficeID: str | None = None
    Business: str | None = None
    Address: Address | None = None
    OpeningHours: OpeningHours | None = None
    Distance: float | None = None
    Availability: bool | None = None
    Position: Position | None = None
    BookingReference: str | None = None


class CreatePrintReply(BaseReply):
    CompletedShipmentInfoCreatePrint: CompletedShipmentInfoCreatePrint | None = None
    Label: Document | None = None
    LabelData: ShipmentLabelData | None = None
    PartnerCode: str | None = None


class PrintLabelReply(BaseReply):
    Label: Document | None = None
    LabelData: ShipmentLabelData | None = None
    PartnerCode: str | None = None


class PrintDocumentReply(BaseReply):
    Label: Document | None = None
    LabelData: ShipmentLabelData | None = None
    DocumentType: Document | None = None


class CreateManifestReply(BaseReply):
    CompletedManifests: CompletedManifests | None = None


class PrintManifestReply(BaseReply):
    Manifest: Document | None = None


class ReturnShipmentReply(BaseReply):
    CompletedShipmentInfo: CompletedReturnInfo | None = None


class CCReserveReply(BaseReply):
    PostOffice: PostOffice | None = None


class CancelShipmentReply(BaseReply):
    CompletedCancel: CompletedCancel | None = None


class InternationalInfo(BaseModel):
    Parcels: Parcels | None = None
    ExporterCustomsReference: str | None = None
    RecipientImporterVatNo: str | None = None
    OriginalExportShipmentNo: str | None = None
    DocumentsOnly: bool | None = None
    DocumentsDescription: str | None = None
    ValueUnder200USDollars: bool | None = None
    ShipmentDescription: str | None = None
    Comments: str | None = None
    InvoiceDate: str | None = None
    TermsOfDelivery: str | None = None
    PurchaseOrderRef: str | None = None


class ConvenientCollect(BaseModel):
    Postcode: str | None = None
    PostOffice: list[PostOffice] | None = Field(None, description='')
    Count: int | None = None
    PostOfficeID: str | None = None


class SpecifiedPostOffice(BaseModel):
    Postcode: str | None = None
    PostOffice: list[PostOffice] | None = Field(None, description='')
    Count: int | None = None
    PostOfficeID: str | None = None


class CancelShipmentReply1(BaseModel):
    CancelShipmentReply: CancelShipmentReply


class CCReserveReply1(BaseModel):
    CCReserveReply: CCReserveReply


class CreateManifestReply1(BaseModel):
    CreateManifestReply: CreateManifestReply


class CreatePrintReply1(BaseModel):
    CreatePrintReply: CreatePrintReply


class PrintDocumentReply1(BaseModel):
    PrintDocumentReply: PrintDocumentReply


class PrintLabelReply1(BaseModel):
    PrintLabelReply: PrintLabelReply


class PrintManifestReply1(BaseModel):
    PrintManifestReply: PrintManifestReply


class ReturnShipmentReply1(BaseModel):
    ReturnShipmentReply: ReturnShipmentReply


class FindRequest(BaseRequest):
    ConvenientCollect: ConvenientCollect | None = None
    SpecifiedPostOffice: SpecifiedPostOffice | None = None
    PAF: PAF | None = None
    SafePlaces: bool | None = None
    NominatedDeliveryDates: NominatedDeliveryDates | None = None
    PostcodeExclusion: PostcodeExclusion | None = None


class FindReply(BaseReply):
    ConvenientCollect: ConvenientCollect | None = None
    SpecifiedPostOffice: SpecifiedPostOffice | None = None
    PAF: PAF | None = None
    SafePlaceList: SafePlaceList | None = None
    NominatedDeliveryDates: NominatedDeliveryDates | None = None
    PostcodeExclusion: PostcodeExclusion | None = None


class DeliveryOptions(BaseModel):
    ConvenientCollect: ConvenientCollect | None = None
    IRTS: bool | None = None
    Letterbox: bool | None = None
    SpecifiedPostOffice: SpecifiedPostOffice | None = None
    SpecifiedNeighbour: str | None = None
    SafePlace: str | None = None
    PIN: int | None = None
    NamedRecipient: bool | None = None
    AddressOnly: bool | None = None
    NominatedDeliveryDate: str | None = None
    PersonalParcel: str | None = None


class FindReply1(BaseModel):
    FindReply: FindReply


class FindRequest1(BaseModel):
    FindRequest: FindRequest


class RequestedShipment(BaseModel):
    DepartmentId: int | None = None
    ShipmentType: str
    ContractNumber: str
    RequestId: int | None = None
    ServiceCode: str
    PrePrinted: bool | None = None
    ShippingDate: str | None = None
    JobReference: str | None = None
    RecipientContact: Contact
    RecipientAddress: Address
    ImporterContact: Contact | None = None
    ImporterAddress: Address | None = None
    ExporterContact: Contact | None = None
    ExporterAddress: Address | None = None
    SenderContact: Contact | None = None
    SenderAddress: Address | None = None
    TotalNumberOfParcels: int | None = None
    TotalShipmentWeight: float | None = None
    Enhancement: Enhancement | None = None
    DeliveryOptions: DeliveryOptions | None = None
    HazardousGoods: HazardousGoods | None = None
    Returns: Returns | None = None
    DropOffInd: str | None = None
    PrintOwnLabel: bool | None = None
    CollectionInfo: CollectionInfo | None = None
    InternationalInfo: InternationalInfo | None = None
    ReferenceNumber1: str | None = None
    ReferenceNumber2: str | None = None
    ReferenceNumber3: str | None = None
    ReferenceNumber4: str | None = None
    ReferenceNumber5: str | None = None
    SpecialInstructions1: str | None = None
    SpecialInstructions2: str | None = None
    SpecialInstructions3: str | None = None
    SpecialInstructions4: str | None = None
    InBoundContact: Contact | None = None
    InBoundAddress: Address | None = None
    InBoundDetails: InBoundDetails | None = None
    ExchangeInstructions1: str | None = None
    ExchangeInstructions2: str | None = None
    ExchangeInstructions3: str | None = None
    ConsignmentHandling: bool | None = None


class CompletedShipmentInfo(BaseModel):
    LeadShipmentNumber: str | None = None
    DeliveryDate: str | None = None
    Status: str
    CompletedShipments: CompletedShipments
    RequestedShipment: RequestedShipment


class CreateShipmentRequest(BaseRequest):
    RequestedShipment: RequestedShipment


class CreateShipmentReply(BaseReply):
    CompletedShipmentInfo: CompletedShipmentInfo | None = None


class CreatePrintRequest(BaseRequest):
    RequestedShipment: RequestedShipment


class CreatePrintRequest1(BaseModel):
    CreatePrintRequest: CreatePrintRequest


class CreateShipmentReply1(BaseModel):
    CreateShipmentReply: CreateShipmentReply


class CreateShipmentRequest1(BaseModel):
    CreateShipmentRequest: CreateShipmentRequest
