# coding: utf-8

"""
    ChannelShipper & Royal Mail Public API

    Import your orders, retrieve your orders and generate labels.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from royal_mail_click_and_drop.models.create_order_response import CreateOrderResponse
from royal_mail_click_and_drop.models.failed_order_response import FailedOrderResponse
from typing import Optional, Set
from typing_extensions import Self

class CreateOrdersResponse(BaseModel):
    """
    CreateOrdersResponse
    """ # noqa: E501
    success_count: Optional[StrictInt] = Field(default=None, alias="successCount")
    errors_count: Optional[StrictInt] = Field(default=None, alias="errorsCount")
    created_orders: Optional[List[CreateOrderResponse]] = Field(default=None, alias="createdOrders")
    failed_orders: Optional[List[FailedOrderResponse]] = Field(default=None, alias="failedOrders")
    __properties: ClassVar[List[str]] = ["successCount", "errorsCount", "createdOrders", "failedOrders"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateOrdersResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in created_orders (list)
        _items = []
        if self.created_orders:
            for _item_created_orders in self.created_orders:
                if _item_created_orders:
                    _items.append(_item_created_orders.to_dict())
            _dict['createdOrders'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in failed_orders (list)
        _items = []
        if self.failed_orders:
            for _item_failed_orders in self.failed_orders:
                if _item_failed_orders:
                    _items.append(_item_failed_orders.to_dict())
            _dict['failedOrders'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateOrdersResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "successCount": obj.get("successCount"),
            "errorsCount": obj.get("errorsCount"),
            "createdOrders": [CreateOrderResponse.from_dict(_item) for _item in obj["createdOrders"]] if obj.get("createdOrders") is not None else None,
            "failedOrders": [FailedOrderResponse.from_dict(_item) for _item in obj["failedOrders"]] if obj.get("failedOrders") is not None else None
        })
        return _obj


